## This generates an ever-increasing number based on the date and build. Useful for CI\CD scenario's.
name: $(date:yyyy.M.d)$(rev:.r) 

## GITHUB: specify the Pull Request Builds in yaml as below.
## Azure Devops: setup Pull Request Builds via "manage repositories" - "Branch Policies" in the Azure Devops UI instead. 
pr:
  branches:
    include:
    - main
    
trigger:
  branches:
    include: 
    - main
  paths:
    exclude:
    - /.vscode/*
    - /docs/*
    - /*.md
    - .editorconfig
    - /**/.editorconfig
    - .gitignore
    - /**/.gitignore

resources:
  repositories:
    - repository: yamlTemplates
      type: github
      name: "#UserName/#RepoName"
      endpoint: #AzureDevopsGithubEndpointName
      #ref: string  # ref name to use; defaults to 'refs/heads/main'

variables:
  # File includes can ONLY have a 'variables' section
  - template: build/authors.yml
  #- group: '#GroupName' # Groups are linked to Azure Devops -> Pipelines > Library > Variable Group. Keep secrets there instead of in the actual source. 
  # Other values as key-value pair, or Groups won't work. https://learn.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#use-a-variable-group
  #- name: Key 
  #  value: 'Value'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Publish nuget package 
  jobs:
  - template: AzDO/yaml/jobs/AzDOArtifacts_publishNugetPackage.yml@yamlTemplates
    parameters:
      azureArtifactsTargetFeed: '#TeamProjectName/#ArtifactsFeedName'
      buildSteps: 
      - task: UseDotNet@2
        displayName: 'Use dotnet 6'
        inputs:
          version: '6.0.x'
      - template: AzDO/yaml/steps/buildAndTest.yml@yamlTemplates
        parameters:
          azureArtifactsSourceFeed: '#TeamProjectName/#ArtifactsFeedName'
          runSettingsFile: 'src/.runsettings'

